#!/usr/bin/env python
# Copyright (C) 2008/2009 Axel Tillequin (bdcht3@gmail.com)
# This code is part of Masr
# published under GPLv2 license

import dbus,code,sys
import readline

readline.parse_and_bind("tab:complete")

bus = dbus.SessionBus()
serv = bus.get_object('org.masr','/serv')
cons = dbus.Interface(serv,"masr.rcon")

def remotecompleter(text,state):
    return cons.complete(text,state)

readline.set_completer(remotecompleter)

ic = code.InteractiveConsole()
prompt = '>>> '
print "Welcome to masr d-bus client."
cons.push('app=screen.app')
print "you are connected to the running Masr() instance: app =",
print cons.push('app')
while 1:
    try:
        s = ic.raw_input(prompt)
        r = cons.push(s)
        if r!=None:
            if len(r)>0: print r,
            prompt = '>>> '
        else:
            prompt = '... '
    except EOFError:
        break
print

