#!/usr/bin/env python
# Copyright (C) 2008/2009 Axel Tillequin (bdcht3@gmail.com) 
# This code is part of Masr
# published under GPLv2 license

import sys

from masr import Masr
import masr.plugins.graph as graph
import masr.plugins.ida as ida


app=Masr()
app.plugins.add(graph)
app.plugins.add(ida)
app.run(args=sys.argv)
